### ISSUE TITLE
Sequentially testing each Servo 

### ISSUE THREAD

**Issue by gilgamesh000** [arduino-libraries/MKRMotorCarrier#14]
How in the world do we sequentially drive the servos or DC motors? For instance: due to the fact that in the .h and .cpp files have only servo1, servo2... or M1, M2... and they have no servo(int ServoMotor) definition or constructor. I am missing something simple here but I am also very new to Arduino/C++ programming Otherwise I have create six additional for loop; or four separate programs. Some how I have to redefine the constructor or create a function and then iterate through that function.

No matter what I have tried when I have tried marrying up to either .setAngle( ) or .setDuty() 

**The code below does not work obviously but should explain my end goal.** 
```
//Test each of the servo motors  //This will test all the connected servo motors
  for (int idx_motorCount = 0; idx_motorCount < 3; idx_motorCount++)
    {
     
     //Servo sweep from 0 to position to 180
     for (int idx_servoAngle = 0; idx_servoAngle < 180; idx_servoAngle+=5)
        {
          ServoMotor(idx_motorCount).setAngle(idx_servoAngle);
          delay(150);
        }
     delay(1200);
     //Servo sweep from 180 to 0
     for (int idx_servoAngle = 180; idx_servoAngle > 0; idx_servoAngle-=5)
        {
          ServoMotor(idx_motorCount).setAngle(idx_servoAngle);                  
          delay(150);
        }        
    } 
```

**Comment by facchinm** [comment]
@gilgamesh000 ,
sometime Arduino libraries tend to make things a bit more verbose but less complicated for beginners.
There's no way to directly iterate over servos (or motors), but since there aren't hundreds of them it is more expressive to repeat the assignment multiple times.
If you absolutely don't want to do this, feel free to create a structure with N servos, like 
```C++
mc::ServoMotor* servo[4] = {&servo1, &servo2, &servo3, &servo4} 
```
then this structure can be used as `servo[idx_motorCount]->setAngle()`
